// <auto-generated />
namespace Go_with_the_Crow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pleaseaddadoptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pleaseaddadoptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201903190259333_please-add-adoptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
